### ISSUE TITLE
github.com/mattes/migrate ?

### ISSUE THREAD

**Issue by mattes** [db-journey/journey#2]
@gravis I just saw this. thanks to @nathany (https://github.com/mattes/migrate/issues/86#issuecomment-279464499). 

I am super confused. What's the plan here? Is this just a fork/ copy with drivers in their own repo? The irony is, I just pointed out why that doesn't make sense in the latest [v3 efforts](https://github.com/mattes/migrate/tree/v3.0-prev), which I've been working on since December.

https://github.com/mattes/migrate/blob/v3.0-prev/FAQ.md#can-i-maintain-my-driver-in-my-own-repository

**Comment by nathany** [comment]
Here is some back story for the separate driver repos: https://github.com/gemnasium/migrate/issues/19

**Comment by gravis** [comment]
Hi @Mattes, for now, it's just a split of the drivers in our migrate fork.
As explained by @Nathany, the idea behind this was to minimize the dependencies bloat in migrate.
The build tags is a very nice idea to solve this issue, we just took another path to resolve this.
We'd also like to allow maintainers to work on drivers without the noise of all the others.

Again, this discussion is 3 months old now, and you there was no sign of you at this time. You can't blame the community to move along, and wait for your inter-contracts time. You did a great job with the v1 (and probably the v3), and I thank you for that.

**Comment by mattes** [comment]
I think there is a misunderstanding, I am not blaming anyone. :-) I asked you before, why not join forces and all contribute to mattes/migrate instead of creating confusion with this copy that doesn't do anything new?

**Comment by gravis** [comment]
ha, good question :)
Mostly because it's going to be different soon: take a look at https://github.com/db-journey/migrate/issues/2 for example. The API of the drivers are going to be updated (I haven't answered on this particular ticket, but I agree with the proposed changes).

AFAIC, the following points are very different between migrate (v1 or v3), and make the 2 projects incompatible on the long term:

- I see journey more as a lib then a swiss army knife, meaning all components are lightweight and independent, except the base "migrate" lib which unifies all drivers. Therefore, I don't see the need to introduce sources for example (except bindata). All that can be done with command line should stay on command line. 
- As it is a lib, it's intended to be used in other projects. That being said, having all drivers in the same repo will make `go get ` to fetch all of them (because they're part of the repo), and their dependencies. I haven't looked enough in your new depencency_tree, but I can see `github.com/docker/docker` is now a dep, that a HUGE project to depend on. Cross-compiling is also an issue when is comes to sqlite3.
- I'm personally only interested in the postgresql driver, since I don't use any of the other ones available. I'm sure @nathany doesn't care for anything else then Cassandra. With a common repo for all of these, the noise will increase with time. All the teams will notified for each PR, issue, broken build, etc. They will slowly start to remove notification until the project will be left alone (there are not many contributors: https://github.com/mattes/migrate/graphs/contributors).

If we find a path where this can be addressed, I would pleased to contribute.

PS: why v3? What happened to v2 :)

**Comment by nathany** [comment]
@mattes Forks are just part of open source. 

With both libraries diverging, I'm curious to see where this goes. There are several other migration libraries for Go as well, each with different strengths.

**Comment by mattes** [comment]
> re:  db-journey/migrate#2

https://github.com/mattes/migrate/blob/v3.0-prev/database/driver.go#L27
https://github.com/mattes/migrate/blob/v3.0-prev/database/postgres/postgres.go#L29

> I see journey more as a lib
>  All that can be done with command line should stay on command line.

completely agreed. the reason why I think https://github.com/mattes/migrate/issues/145 should be done outside of migrate.

> Therefore, I don't see the need to introduce sources for example (except bindata)

I think that's a point for source abstraction. :-)

>having all drivers in the same repo will make go get to fetch all of them (because they're part of the repo)

that's not true, if the packages are structured correctly. see v3.

> I can see github.com/docker/docker is now a dep

see my point above. it's a dep for testing only. it will never make it to any binary build.

> Cross-compiling is also an issue when is comes to sqlite3.

v3 solves that by build tags. separate repos don't fix this.

> With a common repo for all of these, the noise will increase with time.

I agree with that. I think people are trained to filter fast these days though. Personally this is not a big deal for me. 

> why v3? What happened to v2 :)

v2 exists internally here. its being used, but didn't got published because sensitive data was baked into the repo. that's bad obviously.

> Forks are just part of open source.

There is no doubt about that.

**Comment by danilobuerger** [comment]
@mattes I never like forking. It's a hassle, it distracts, and it divides. However, as already mentioned by @gravis, you left us no choice. Life goes on, and so do our needs with a migration library. Just because you are active now, shouldn't matter for the decision we have already taken. No need to dwell on the past though, let's move forward. As @gravis already outlined, the philosophy seems different between the two projects so we will end up with two different products.

As a side note: One thing we haven't done yet, but should do, is proper attribution to your work and license.

**Comment by mattes** [comment]
I'm upset that you think that way, especially since I'm offering a working solution.

**Comment by danilobuerger** [comment]
What part is upsetting you?

**Comment by nathany** [comment]
@mattes Don't Worry, Be Happy 😃

**Comment by mattes** [comment]
@danilobuerger 
> Just because you are active now, shouldn't matter for the decision we have already taken. 

You should be able to reflect on decisions made in the past and eventually come to a better decision. :-) Like I outlined above, I don't see a difference between what db-journey wants to achieve and what my latest efforts are already providing.

I think it would be great to work all together and provide a great solution for everyone looking to run migrations against databases. What do you want to accomplish with db-journey? How will it be different?

**Comment by danilobuerger** [comment]
I think @gravis made the differences clear. I don't want the drivers to be in the same repository. On a personal note: I don't want to be a maintainer of somebody else's personal repository. I either work on my own or on organizational repositories as a maintainer. 

You are welcome to join us here and work together with us on journey, consider it a fresh start.

**Comment by mattes** [comment]
Why do you want the drivers in different repos and why wouldn't you want to contribute to mattes/migrate?

**Comment by danilobuerger** [comment]
> Why do you want the drivers to be in the same repo

I don't want the drivers to be in the same repository (probably what you meant to ask). Because:
* Less noise
* No dependency hell
* Organizing issues where they belong

> why wouldn't you want to contribute to mattes/migrate?

I didn't say that, I said I don't want to be a maintainer of somebody else's personal repository. Even if I had contributed to your repository, see https://github.com/mattes/migrate/issues/82. I asked the question on 15 Feb *2016*. To this day there is no answer from you in this issue. I consider that rude and disrespectful. If I had taken the time to do a PR for anything, it would have been a waste of time. You wouldn't have looked at it for 10 more months.

I really don't understand why we are discussing this anyway. Forking is an integral part of open source culture. We were not happy with how you handled the management of the project, so we forked it. Why would you even care? It doesn't matter if there are 10 or 11 migration libraries for go out there.

As I said before, you are welcome to join us here and work with us as a group.

**Comment by mattes** [comment]
I understand your frustration. I think at this point there is no way back for you, as you already made a decision for yourself.

What I'm asking you, since you're asking for a fresh start, actually do a fresh start. Don't just copy the code over from migrate. For everything else, please make sure to add proper backlinks and ideally don't change the license. Maybe migrate can benefit from work done being here, too.

**Comment by danilobuerger** [comment]
> please make sure to add proper backlinks and ideally don't change the license.

As I mentioned above:

> As a side note: One thing we haven't done yet, but should do, is proper attribution to your work and license.

I am certain we are going to fulfill the requirements of your license to the fullest.
