### ISSUE TITLE
Passing negative migration numbers throws a "flag not defined" error

### ISSUE THREAD

**Issue by rmthamer** [db-journey/journey#4]
journey --url "cassandra://127.0.0.1:9042/test?protocol=4" --path ./migrations migrate migrate -1
Incorrect Usage: flag provided but not defined: -1

NAME:
   journey migrate migrate - Apply migrations -n|+n

USAGE:
   journey migrate migrate <n>
2017/08/01 16:19:38 flag provided but not defined: -1

**Comment by nathany** [comment]
Likewise with postgres.

**Comment by gravis** [comment]
Sorry for the (very) long delay. That's because we're using https://github.com/urfave/cli instead of plain flags. We need to fix this of course.
We're currently focusing on Java support in Gemnasium, and I won't have availability before some time to work on this. Any PR is welcome in the meantime :)

**Comment by nathany** [comment]
#6 should close this issue

**Comment by gravis** [comment]
Good catch
Thanks
