### ISSUE TITLE
strconv.Atoi: parsing "migrate": invalid syntax

### ISSUE THREAD

**Issue by nathany** [db-journey/journey#8]
This error started occurring recently. Maybe related to a change in https://github.com/urfave/cli?

```
journey -url "postgres://u:p@localhost/db?sslmode=disable" -path ./db migrate migrate +1
FATA[0000] Unable to parse param <n>
error="strconv.Atoi: parsing \"migrate\": invalid syntax"
```

**Comment by nathany** [comment]
Yes, commit c6eb2a051026c083d4e33591f8d6e95d5f4189dc of urfave/cli works. bisecting now

**Comment by nathany** [comment]
> "df562bf1a8626f2d16f91fcbf7230a5bdca3d592 is the first bad commit"

https://github.com/urfave/cli/pull/686/files

**Comment by baude** [comment]
are you using the skipargreorder ?

**Comment by nathany** [comment]
I'm not entirely sure what journey uses.

I think the relevant code is in https://github.com/db-journey/journey/blob/master/commands/migrate_commands.go which doesn't look like it's using that option.

**Comment by baude** [comment]
I'd be inclined to try it with that option.  I dont know this application very well but it seems like after -path you have a path argument and then some stuff that isn't really an option ?

**Comment by gravis** [comment]
Thanks @nathany for the investigation.
@baude : `path` and `url` are global flags, hence they're before the [command](https://github.com/db-journey/journey/blob/master/commands/commands.go#L8) `migrate`, then the [subcommand](https://github.com/db-journey/journey/blob/master/commands/migrate_commands.go#L155) `migrate` with the arg `+1`.

Since this was working fine until this [commit](https://github.com/urfave/cli/pull/686) , I consider this a bug in `cli`, and we should investigate there instead, unless there's something I didn't catch here.

**Comment by jszwedko** [comment]
Apologies for the delay in responding to this and for introducing this regression. I believe I've fixed this in https://github.com/urfave/cli/pull/697 (and added a test case).
